#!/bin/bash

#
# Expand template after docker creation
#

while [ ! -f /var/lib/docker/volumes/piler_piler_etc/_data/piler.conf ]
do
  sleep 2
done

/usr/sbin/e-smith/expand-template /var/lib/docker/volumes/piler_piler_etc/_data/config-site.php
