#!/bin/bash

#
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

input=$(cat)
action=$(jq -r .action <<<"$input")
protocol=$(jq -r .location.protocol <<<"$input")
host=$(jq -r .location.hostname <<<"$input")
vhost=$(/usr/sbin/e-smith/config getprop piler Vhost)
DomainName=$(/usr/sbin/e-smith/config get DomainName)

if [[ $action == "app-info" ]]; then
    if [[ $vhost == '' ]];then
        printf '{"url":"%s"}' "${protocol}//piler.${DomainName}"
    else 
        printf '{"url":"%s"}' "${protocol}//${vhost}"
    fi
fi
